# Generated by Django 4.2 on 2026-08-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_systemsettings_studentclass_joinrequest_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="custom_model_dir",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="自定义模型目录"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="rec_model",
            field=models.CharField(
                choices=[("official", "官方 PP-OCRv4"), ("custom", "自定义微调模型")],
                default="official",
                max_length=20,
                verbose_name="识别模型",
            ),
        ),
    ]
