# Generated by Django 4.2 on 2026-08-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0003_systemsettings_custom_model_dir_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="finetuned_model_dir",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="微调模型目录"
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="rec_model",
            field=models.CharField(
                choices=[
                    ("official", "默认 OCR（官方 PP-OCRv4）"),
                    ("finetuned", "OCR 微调模型"),
                    ("db_det", "DB 文本检测"),
                    ("crnn_rec", "CRNN 文字识别"),
                    ("custom", "自定义微调模型"),
                ],
                default="official",
                max_length=20,
                verbose_name="识别模型",
            ),
        ),
    ]
