# Generated by Django 4.2 on 2026-08-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0004_systemsettings_finetuned_model_dir_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "登录"),
                    ("logout", "登出"),
                    ("create_student", "添加学生"),
                    ("edit_student", "编辑学生"),
                    ("reset_password", "重置密码"),
                    ("delete_student", "删除学生"),
                    ("create_class", "创建班级"),
                    ("archive_class", "归档班级"),
                    ("unarchive_class", "恢复班级"),
                    ("approve_request", "通过申请"),
                    ("reject_request", "拒绝申请"),
                    ("save_settings", "保存设置"),
                    ("export_records", "导出记录"),
                    ("ocr_detect", "OCR 识别"),
                    ("upload_image", "上传图片"),
                    ("export_logs", "导出日志"),
                ],
                max_length=30,
                verbose_name="操作类型",
            ),
        ),
    ]
