# Generated by Django 4.2 on 2026-08-19 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OCRRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="ocr_images/", verbose_name="Uploaded Image"
                    ),
                ),
                (
                    "result_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="OCR Result Text"
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Confidence Score"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "OCR Result",
                "verbose_name_plural": "OCR Results",
                "ordering": ["-created_at"],
            },
        ),
    ]
