# Generated by Django 4.2 on 2026-08-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_demo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrrecord",
            name="compliance_issues",
            field=models.TextField(blank=True, null=True, verbose_name="合规问题"),
        ),
        migrations.AddField(
            model_name="ocrrecord",
            name="is_compliant",
            field=models.BooleanField(default=False, verbose_name="是否合规"),
        ),
        migrations.AddField(
            model_name="ocrrecord",
            name="missing_fields",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="缺失字段"
            ),
        ),
    ]
