# Generated by Django 4.2 on 2026-08-20 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "ocr_demo",
            "0002_ocrrecord_compliance_issues_ocrrecord_is_compliant_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="数据集名称")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="数据集描述"),
                ),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[
                            ("food_label", "食品标签"),
                            ("general", "通用文字"),
                            ("custom", "自定义"),
                        ],
                        default="food_label",
                        max_length=20,
                        verbose_name="数据集类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_datasets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "训练数据集",
                "verbose_name_plural": "训练数据集",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="训练任务名称")),
                (
                    "model_type",
                    models.CharField(
                        default="paddleocr", max_length=50, verbose_name="模型类型"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("stopped", "已停止"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="训练状态",
                    ),
                ),
                (
                    "progress",
                    models.FloatField(default=0, verbose_name="训练进度（0-100）"),
                ),
                ("epochs", models.IntegerField(default=10, verbose_name="训练轮数")),
                (
                    "batch_size",
                    models.IntegerField(default=16, verbose_name="批次大小"),
                ),
                (
                    "learning_rate",
                    models.FloatField(default=0.001, verbose_name="学习率"),
                ),
                (
                    "log_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="training_logs/",
                        verbose_name="训练日志文件",
                    ),
                ),
                (
                    "model_path",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="模型保存路径",
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="训练指标"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_jobs",
                        to="ocr_demo.trainingdataset",
                        verbose_name="训练数据集",
                    ),
                ),
            ],
            options={
                "verbose_name": "训练任务",
                "verbose_name_plural": "训练任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="training_images/", verbose_name="训练图片"
                    ),
                ),
                (
                    "annotation_text",
                    models.TextField(blank=True, null=True, verbose_name="标注文本"),
                ),
                (
                    "annotation_bbox",
                    models.JSONField(
                        blank=True, default=list, null=True, verbose_name="标注边界框"
                    ),
                ),
                (
                    "annotation_status",
                    models.CharField(
                        choices=[
                            ("pending", "待标注"),
                            ("annotated", "已标注"),
                            ("verified", "已审核"),
                            ("rejected", "已驳回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="标注状态",
                    ),
                ),
                (
                    "annotated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="标注时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "annotated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="annotated_images",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="标注者",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="ocr_demo.trainingdataset",
                        verbose_name="所属数据集",
                    ),
                ),
            ],
            options={
                "verbose_name": "训练图片",
                "verbose_name_plural": "训练图片",
                "ordering": ["-created_at"],
            },
        ),
    ]
