# Generated by Django 4.2 on 2026-08-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_demo", "0003_trainingdataset_trainingjob_trainingimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrrecord",
            name="packaging_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Box", "盒装"),
                    ("Bottle", "瓶装"),
                    ("Can", "罐装"),
                    ("Label", "标签"),
                    ("Bag", "袋装"),
                    ("Cup", "杯装"),
                ],
                default="",
                max_length=20,
                verbose_name="包装分类",
            ),
        ),
        migrations.AlterField(
            model_name="trainingimage",
            name="annotation_status",
            field=models.CharField(
                choices=[
                    ("pending", "待标注"),
                    ("pre_annotated", "待审核"),
                    ("annotated", "已修正"),
                    ("verified", "已审核"),
                    ("rejected", "已驳回"),
                ],
                default="pending",
                max_length=20,
                verbose_name="标注状态",
            ),
        ),
    ]
