# Generated by Django 4.2 on 2026-08-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_demo", "0004_ocrrecord_packaging_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocrrecord",
            name="image",
            field=models.ImageField(
                max_length=255, upload_to="ocr_images/", verbose_name="Uploaded Image"
            ),
        ),
        migrations.AlterField(
            model_name="trainingimage",
            name="image",
            field=models.ImageField(
                max_length=255, upload_to="training_images/", verbose_name="训练图片"
            ),
        ),
        migrations.AlterField(
            model_name="trainingjob",
            name="log_file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="training_logs/",
                verbose_name="训练日志文件",
            ),
        ),
    ]
