# Generated by Django 4.2 on 2026-08-22 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_demo", "0005_alter_ocrrecord_image_alter_trainingimage_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                ("description", models.TextField(blank=True, verbose_name="模板描述")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "标签模板",
                "verbose_name_plural": "标签模板",
                "ordering": ["-is_active", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="LabelField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="字段名称")),
                (
                    "keywords",
                    models.CharField(
                        help_text="逗号分隔的关键词",
                        max_length=255,
                        verbose_name="关键词",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="ocr_demo.labeltemplate",
                        verbose_name="所属模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "标签字段",
                "verbose_name_plural": "标签字段",
                "ordering": ["order", "id"],
            },
        ),
    ]
