# Generated by Django 4.2 on 2026-08-22 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ocr_demo", "0006_labeltemplate_labelfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_path",
                    models.CharField(max_length=255, verbose_name="评测数据文件"),
                ),
                (
                    "model_dir",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="推理模型目录（空=官方 PP-OCRv4）",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "评估中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "char_accuracy",
                    models.FloatField(
                        blank=True, null=True, verbose_name="字符准确率(%)"
                    ),
                ),
                (
                    "line_accuracy",
                    models.FloatField(
                        blank=True, null=True, verbose_name="整行准确率(%)"
                    ),
                ),
                ("total_lines", models.IntegerField(default=0, verbose_name="总行数")),
                (
                    "exact_lines",
                    models.IntegerField(default=0, verbose_name="整行一致数"),
                ),
                (
                    "metrics",
                    models.JSONField(blank=True, default=dict, verbose_name="详细指标"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="失败原因"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "模型评估",
                "verbose_name_plural": "模型评估",
                "ordering": ["-created_at"],
            },
        ),
    ]
