# Generated by Django 4.2 on 2026-08-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_demo", "0007_evaluationrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingjob",
            name="base_model",
            field=models.CharField(
                choices=[
                    ("official", "官方 PP-OCRv4 rec 预训练"),
                    ("local", "本地最新微调 checkpoint"),
                ],
                default="official",
                max_length=20,
                verbose_name="预训练起点",
            ),
        ),
        migrations.AddField(
            model_name="trainingjob",
            name="cosine_lr",
            field=models.BooleanField(default=True, verbose_name="Cosine 学习率"),
        ),
        migrations.AddField(
            model_name="trainingjob",
            name="freeze_backbone",
            field=models.BooleanField(default=False, verbose_name="冻结 Backbone"),
        ),
        migrations.AddField(
            model_name="trainingjob",
            name="image_size",
            field=models.CharField(
                default="320", max_length=10, verbose_name="图片宽度"
            ),
        ),
        migrations.AddField(
            model_name="trainingjob",
            name="optimizer",
            field=models.CharField(
                choices=[
                    ("adam", "Adam"),
                    ("adamw", "AdamW"),
                    ("momentum", "Momentum (SGD)"),
                ],
                default="adam",
                max_length=20,
                verbose_name="优化器",
            ),
        ),
    ]
