# Generated by Django 4.2 on 2026-08-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_demo", "0009_add_standard_label_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingimage",
            name="structured_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                null=True,
                verbose_name="结构化字段（品名/类型/日期/配料等）",
            ),
        ),
    ]
